### Python Libraries For Data Science
- Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing, processing and analysing the data.
- There are nearly 20 python libraries for Data Science. Top five python libraries are
- TensorFlow
- NumPy
- SciPy
- Pandas
- Matplotlib
- In those libraries, Numpy and Pandas are the first choice to the data scientists who are aware of the technologies.

### NumPy: (Numerical Python)¶
- Numpy is Base N-Dimensional Array Package, is a python library and a fundamental package for scientific computing in Python. It is used to create multidimensional arrays for fast operations. Use the following import conversion.
- import numpy as np

### Introduction to NumPy
- The learning objectives of this section are:
- Understand advantages of vectorised code using NumPy (over standard python ways)
- Create NumPy arrays
- Convert lists and tuples to NumPy arrays
- Create (initialise) arrays
- Inspect the structure and content of arrays
- Subset, slice, index and iterate through arrays
- Compare computation times in NumPy and standard Python lists

- There are 3 arrys 1d array,2d array,3d array

In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([1])

array([1])

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [9]:
arr_2d = np.array([[1,2,3],[2,3,4]])
arr_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
type(arr_2d)

numpy.ndarray

In [14]:
arr_3d = np.array([[[1,2],[2,5],[3,6]]])
arr_3d

array([[[1, 2],
        [2, 5],
        [3, 6]]])

In [16]:
l1=[1,2,3,4]
#l1**2
# 1,4,9,16
l2=[]
for i in l1:
    l2.append(i**2)
l2

[1, 4, 9, 16]

In [39]:
%time
res=lambda x : x**2
list(map(res,l1))

Wall time: 0 ns


[1, 4, 9, 16]

In [18]:
[i**2 for i in l1]

[1, 4, 9, 16]

In [19]:
s = np.array([1,2,3,4])
s**2

array([ 1,  4,  9, 16], dtype=int32)

In [22]:
s2 = np.array([3,4,5,6])
s+s2

array([ 4,  6,  8, 10])

In [23]:
s

array([1, 2, 3, 4])

In [38]:
%time
s1/s2

Wall time: 0 ns


array([1., 1., 1., 1.])

In [25]:
s1 + s2

array([ 6,  8, 10, 12])

In [26]:
s1

array([3, 4, 5, 6])

In [31]:
s1[0]

3

In [32]:
s1[1]

4

In [33]:
arr_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [35]:
arr_2d[0][2]

3

In [46]:
r = range(0,10,2)
type(r)

range

In [47]:
a = np.arange(10)
a
type(a)

numpy.ndarray

In [42]:
a1 = np.arange(1,10,2)
a1

array([1, 3, 5, 7, 9])

In [45]:
a2 = np.array(range(1,10,2))
a2

array([1, 3, 5, 7, 9])

In [51]:
a3 = np.linspace(1,10,100)
a3

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [52]:
range(1.5,10.5)

TypeError: 'float' object cannot be interpreted as an integer

In [53]:
a1 = np.arange(1.5,10.5,2)
a1

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [58]:
a2 = np.linspace(1.2,90.4,10)
a2

array([ 1.2       , 11.11111111, 21.02222222, 30.93333333, 40.84444444,
       50.75555556, 60.66666667, 70.57777778, 80.48888889, 90.4       ])

In [59]:
type(a2[0])

numpy.float64

In [60]:
arr_3d

array([[[1, 2],
        [2, 5],
        [3, 6]]])

In [62]:
arr_3d.reshape(2,3)

array([[1, 2, 2],
       [5, 3, 6]])

In [66]:
arr_3d.reshape(4)

ValueError: cannot reshape array of size 6 into shape (4,)

In [67]:
arr_3d.reshape(-1)

array([1, 2, 2, 5, 3, 6])

In [68]:
arr_3d.reshape(3,-1)

array([[1, 2],
       [2, 5],
       [3, 6]])

In [70]:
arr_3d.reshape(-1,3)

array([[1, 2, 2],
       [5, 3, 6]])

In [71]:
arr_3d


array([[[1, 2],
        [2, 5],
        [3, 6]]])

In [74]:
arr_3d.reshape(3,-1)

array([[1, 2],
       [2, 5],
       [3, 6]])

In [76]:
arr_3d.reshape(-1,2)

array([[1, 2],
       [2, 5],
       [3, 6]])

In [78]:
arr_3d.reshape(2,-1)

array([[1, 2, 2],
       [5, 3, 6]])

In [79]:
arr_3d.reshape(-1)

array([1, 2, 2, 5, 3, 6])

In [83]:
a =np.array([[[1,2,3],[4,5,6]],[[3,4,5],[5,6,7]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [5, 6, 7]]])

In [84]:
a.itemsize

4

In [85]:
a.ndim

3

In [86]:
a.shape

(2, 2, 3)

In [87]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [91]:
help(np.shape)

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    alen
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



In [92]:
d = np.arange(1,500,9)

In [93]:
d

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100, 109,
       118, 127, 136, 145, 154, 163, 172, 181, 190, 199, 208, 217, 226,
       235, 244, 253, 262, 271, 280, 289, 298, 307, 316, 325, 334, 343,
       352, 361, 370, 379, 388, 397, 406, 415, 424, 433, 442, 451, 460,
       469, 478, 487, 496])

In [98]:
d[55]# 0 - 55

496

In [102]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [103]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [105]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [107]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [108]:
np.eye(100,100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [115]:
np.eye((10),dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [116]:
np.eye((10),k=5)

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [117]:
np.eye((10),k=-5)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [118]:
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [5, 6, 7]]])

In [119]:
a.T

array([[[1, 3],
        [4, 5]],

       [[2, 4],
        [5, 6]],

       [[3, 5],
        [6, 7]]])

In [120]:
a2

array([ 1.2       , 11.11111111, 21.02222222, 30.93333333, 40.84444444,
       50.75555556, 60.66666667, 70.57777778, 80.48888889, 90.4       ])

In [121]:
a2.T

array([ 1.2       , 11.11111111, 21.02222222, 30.93333333, 40.84444444,
       50.75555556, 60.66666667, 70.57777778, 80.48888889, 90.4       ])

In [122]:
a1

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [123]:
a1.T

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [124]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpose(x, (1, 0, 2)).s

In [125]:
np.transpose(a1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [126]:
a = [[1,2],[3,4]]
a

[[1, 2], [3, 4]]

In [127]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [129]:
np.random.random((2,10))

array([[0.95427546, 0.1326504 , 0.22894682, 0.74371726, 0.4385354 ,
        0.11478747, 0.62263578, 0.66853354, 0.9430837 , 0.95571176],
       [0.45508469, 0.30830088, 0.22235491, 0.4939628 , 0.77993464,
        0.12235684, 0.47530996, 0.53003211, 0.04520699, 0.66449556]])

In [131]:
f = np.random.randint(100,500,(25,6))
f

array([[384, 268, 260, 249, 269, 349],
       [223, 330, 399, 390, 455, 492],
       [292, 225, 258, 464, 112, 239],
       [464, 420, 221, 115, 140, 382],
       [441, 245, 394, 263, 202, 424],
       [290, 489, 342, 367, 358, 380],
       [487, 206, 486, 274, 200, 187],
       [194, 122, 359, 158, 473, 388],
       [136, 172, 486, 366, 448, 489],
       [155, 410, 126, 349, 245, 249],
       [241, 317, 268, 125, 224, 275],
       [165, 440, 302, 283, 415, 397],
       [216, 416, 296, 327, 400, 422],
       [296, 238, 326, 277, 363, 145],
       [112, 209, 188, 234, 151, 349],
       [399, 155, 393, 355, 369, 449],
       [481, 476, 456, 202, 191, 327],
       [444, 233, 287, 468, 183, 164],
       [334, 268, 212, 114, 487, 211],
       [178, 204, 250, 374, 126, 313],
       [129, 319, 388, 300, 429, 259],
       [392, 357, 161, 217, 225, 380],
       [472, 488, 378, 220, 266, 133],
       [433, 309, 162, 269, 294, 161],
       [278, 461, 187, 238, 375, 229]])

In [132]:
f.shape

(25, 6)

In [133]:
f[1:]

array([[223, 330, 399, 390, 455, 492],
       [292, 225, 258, 464, 112, 239],
       [464, 420, 221, 115, 140, 382],
       [441, 245, 394, 263, 202, 424],
       [290, 489, 342, 367, 358, 380],
       [487, 206, 486, 274, 200, 187],
       [194, 122, 359, 158, 473, 388],
       [136, 172, 486, 366, 448, 489],
       [155, 410, 126, 349, 245, 249],
       [241, 317, 268, 125, 224, 275],
       [165, 440, 302, 283, 415, 397],
       [216, 416, 296, 327, 400, 422],
       [296, 238, 326, 277, 363, 145],
       [112, 209, 188, 234, 151, 349],
       [399, 155, 393, 355, 369, 449],
       [481, 476, 456, 202, 191, 327],
       [444, 233, 287, 468, 183, 164],
       [334, 268, 212, 114, 487, 211],
       [178, 204, 250, 374, 126, 313],
       [129, 319, 388, 300, 429, 259],
       [392, 357, 161, 217, 225, 380],
       [472, 488, 378, 220, 266, 133],
       [433, 309, 162, 269, 294, 161],
       [278, 461, 187, 238, 375, 229]])

In [134]:
f[3]

array([464, 420, 221, 115, 140, 382])

In [136]:
f[[3,4,5]]

array([[464, 420, 221, 115, 140, 382],
       [441, 245, 394, 263, 202, 424],
       [290, 489, 342, 367, 358, 380]])

In [140]:
f[-5:]

array([[129, 319, 388, 300, 429, 259],
       [392, 357, 161, 217, 225, 380],
       [472, 488, 378, 220, 266, 133],
       [433, 309, 162, 269, 294, 161],
       [278, 461, 187, 238, 375, 229]])

In [146]:
f[:2]

array([[384, 268, 260, 249, 269, 349],
       [223, 330, 399, 390, 455, 492]])

In [148]:
f[2,[2,3]]

array([258, 464])

In [150]:
f[[2,3,4],[2,3,4]]

array([258, 115, 202])

In [151]:
a

[[1, 2], [3, 4]]

In [152]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [153]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [154]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [155]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [156]:
np.linalg.det(a)

-2.0000000000000004

In [157]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [158]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [159]:
a

[[1, 2], [3, 4]]

In [162]:
np.full((1,3),10)

array([[10, 10, 10]])

In [169]:
s = np.array([[[1,2],[9,8]],[[1,2],[7,8]]])
s

array([[[1, 2],
        [9, 8]],

       [[1, 2],
        [7, 8]]])

In [170]:
s.flatten()

array([1, 2, 9, 8, 1, 2, 7, 8])

In [173]:
help(np.tile)

Help on function tile in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A`

In [177]:
np.tile(s,4)

array([[[1, 2, 1, 2, 1, 2, 1, 2],
        [9, 8, 9, 8, 9, 8, 9, 8]],

       [[1, 2, 1, 2, 1, 2, 1, 2],
        [7, 8, 7, 8, 7, 8, 7, 8]]])

In [176]:
s

array([[[1, 2],
        [9, 8]],

       [[1, 2],
        [7, 8]]])

In [184]:
s.reshape(2,-1) # function

array([[1, 2, 9, 8],
       [1, 2, 7, 8]])

In [180]:
s.size # Attribute

8

In [181]:
s

array([[[1, 2],
        [9, 8]],

       [[1, 2],
        [7, 8]]])

In [185]:
import math

In [186]:
math.pi # package.attribute

3.141592653589793

In [187]:
math.pow(2,3) # package.function

8.0

In [188]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [189]:
help(math.tan)

Help on built-in function tan in module math:

tan(x, /)
    Return the tangent of x (measured in radians).



###  docs.scipy.org/doc